In [1]:
import numpy as np

In [2]:
l = [1.0,2.0,3.0,5.0]

# List to Array by numpy

In [3]:
l

[1.0, 2.0, 3.0, 5.0]

In [4]:
e=np.array(l)

In [5]:
type(e)

numpy.ndarray

In [6]:
np.empty([3,3]).shape

(3, 3)

In [7]:
np.zeros([3,5]).shape

(3, 5)

In [8]:
np.ones([8,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
g = np.array([2.0,3.0,4.0,6.0])

In [10]:
g

array([2., 3., 4., 6.])

# stacking arrays in vectors

In [11]:
from numpy import vstack
from numpy import hstack

In [12]:
vstack((l,g)).shape

(2, 4)

In [13]:
hstack((l,g)).shape

(8,)

In [14]:
l

[1.0, 2.0, 3.0, 5.0]

In [15]:
g

array([2., 3., 4., 6.])

# Vector Arthmetic

In [16]:
l + g

array([ 3.,  5.,  7., 11.])

In [17]:
l * g

array([ 2.,  6., 12., 30.])

In [18]:
l * np.array(10)


array([10., 20., 30., 50.])

In [19]:
t=np.array([6,4])

In [31]:
t

array([6, 4])

In [20]:
l + t

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Vectors reshapeing 

In [21]:
l1=np.reshape(l,(2,2))

In [22]:
g1=np.reshape(g,(2,2))

In [23]:
l1/g1

array([[0.5       , 0.66666667],
       [0.75      , 0.83333333]])

In [24]:
l1 * g1

array([[ 2.,  6.],
       [12., 30.]])

In [25]:
type(g1)

numpy.ndarray

# Vector Dot Product

In [26]:
g1.dot(l1)

array([[11., 19.],
       [22., 38.]])

In [27]:
l1.dot(g1)

array([[10., 15.],
       [26., 39.]])

# Vector Scalar Arthmetic

In [28]:
#define scalar
s = 0.5

In [29]:
l1

array([[1., 2.],
       [3., 5.]])

In [30]:
s * l1

array([[0.5, 1. ],
       [1.5, 2.5]])