In [1]:
import numpy as np

In [2]:
l = [1.0,2.0,3.0,5.0]

# List to Array by numpy

In [3]:
l

[1.0, 2.0, 3.0, 5.0]

In [4]:
e=np.array(l)

In [5]:
type(e)

numpy.ndarray

In [7]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.52166653e-321],
       [4.03532068e-270, 1.73157072e-260, 1.02218071e-282]])

In [7]:
np.zeros([3,5]).shape

(3, 5)

In [8]:
np.ones([8,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
g = np.array([2.0,3.0,4.0,6.0])

In [21]:
g

array([2., 3., 4., 6.])

# stacking arrays in vectors

In [22]:
from numpy import vstack
from numpy import hstack

In [23]:
vstack((l,g))

array([[1., 2., 3., 5.],
       [2., 3., 4., 6.]])

In [24]:
hstack((l,g))

array([1., 2., 3., 5., 2., 3., 4., 6.])

In [25]:
l

[1.0, 2.0, 3.0, 5.0]

In [26]:
g

array([2., 3., 4., 6.])

# Vector Arthmetic

In [29]:
l + g

array([ 3.,  5.,  7., 11.])

In [30]:
l * g

array([ 2.,  6., 12., 30.])

In [31]:
l * np.array(10)


array([10., 20., 30., 50.])

In [32]:
t=np.array([6,4])

In [33]:
t

array([6, 4])

In [34]:
l * t

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Vectors reshapeing 

In [35]:
l1=np.reshape(l,(2,2))

In [36]:
g1=np.reshape(g,(2,2))

In [37]:
l1/g1

array([[0.5       , 0.66666667],
       [0.75      , 0.83333333]])

In [38]:
l1 * g1

array([[ 2.,  6.],
       [12., 30.]])

In [39]:
type(g1)

numpy.ndarray

# Vector Dot Product

In [40]:
g1.dot(l1)

array([[11., 19.],
       [22., 38.]])

In [41]:
l1.dot(g1)

array([[10., 15.],
       [26., 39.]])

# Vector Scalar Arthmetic

In [42]:
#define scalar
s = 0.5

In [43]:
l1

array([[1., 2.],
       [3., 5.]])

In [44]:
s * l1

array([[0.5, 1. ],
       [1.5, 2.5]])

# Normalization L1 & L2 

In [56]:
from numpy.linalg import norm
from math import inf

In [72]:
def norm_stats(n2):
    l1_norm=norm(n2,1)
    l2_norm = norm(n2)
    max_norm = norm(n2,inf)
    print('L1 norm :',l1_norm,'L2 norm:',l2_norm,'Max Norm:',max_norm)
    

In [73]:
norm_stats(n2)

L1 norm : 6.0 L2 norm: 3.7416573867739413 Max Norm: 3.0


In [70]:
norm_stats(l1)

7.0 6.244997998398398 8.0


In [54]:
l1_norm=norm(n2,1)

In [60]:
l2_norm = norm(n2)

In [61]:
max_norm = norm(n2,inf)

In [64]:
l1_norm;
l2_norm ;
max_norm

3.0

In [65]:
l1_norm,l2_norm,max_norm

(6.0, 3.7416573867739413, 3.0)

In [75]:
abs(3.99)

3.99

# Matrix Arthimetic


In [77]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3],[4,5,6]])

In [79]:
A + B

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [80]:
A * B

array([[ 1,  4,  9],
       [16, 25, 36]])

In [81]:
A - B

array([[0, 0, 0],
       [0, 0, 0]])

In [82]:
G = np.array([[0.5,0.5,0.5],[0.5,0.5,0.5]])

In [83]:
A - G

array([[0.5, 1.5, 2.5],
       [3.5, 4.5, 5.5]])

In [84]:
A/G

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [85]:
A/B

array([[1., 1., 1.],
       [1., 1., 1.]])

# Matrix Dot Products

In [91]:
T = np.array([[2,3],[4,5]])

In [94]:
F = np.array([[1,2],[2,3],[4,5]])

In [95]:
T.dot(F)

array([[24, 33],
       [38, 53]])

In [96]:
F.dot(T)

array([[10, 13, 16],
       [16, 21, 26],
       [28, 37, 46]])

In [97]:
F.shape

(3, 2)

In [98]:
T.shape

(2, 3)

In [99]:
A.shape

(2, 3)

In [100]:
B.shape

(2, 3)

In [101]:
B1=B.reshape(3,2)

In [102]:
B1.shape


(3, 2)

In [103]:
A.dot(B1)

array([[22, 28],
       [49, 64]])

In [105]:
B1.dot(A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [106]:
B1 * 5

array([[ 5, 10],
       [15, 20],
       [25, 30]])