In [1]:
import numpy as np

In [2]:
l = [1.0,2.0,3.0,5.0]

In [3]:
l

[1.0, 2.0, 3.0, 5.0]

In [4]:
e=np.array(l)

In [6]:
type(e)

numpy.ndarray

In [11]:
np.empty([3,3]).shape

(3, 3)

In [10]:
np.zeros([3,5]).shape

(3, 5)

In [12]:
np.ones([8,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
g = np.array([2.0,3.0,4.0,6.0])

In [14]:
g

array([2., 3., 4., 6.])

In [17]:
from numpy import vstack
from numpy import hstack

In [20]:
vstack((l,g)).shape

(2, 4)

In [21]:
hstack((l,g)).shape

(8,)

In [22]:
l

[1.0, 2.0, 3.0, 5.0]

In [23]:
g

array([2., 3., 4., 6.])

In [24]:
l + g

array([ 3.,  5.,  7., 11.])

In [25]:
l * g

array([ 2.,  6., 12., 30.])

In [28]:
l * np.array(10)


array([10., 20., 30., 50.])

In [30]:
t=np.array([6,4])

In [31]:
t

array([6, 4])

In [33]:
l + t

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [35]:
l1=np.reshape(l,(2,2))

In [36]:
g1=np.reshape(g,(2,2))

In [37]:
l1/g1

array([[0.5       , 0.66666667],
       [0.75      , 0.83333333]])

In [38]:
l1 * g1

array([[ 2.,  6.],
       [12., 30.]])

In [39]:
type(g1)

numpy.ndarray